### PR TITLE
TAN-2137: Create patient letter creation modal (Attempt 2)

### PR DESCRIPTION
**Pull request by Alastair-L**
### Changes

Card: TAN-2137

There were also a few small refactors:
- Document submission logic was moved from the DocumentPane to the DocumentModal
- Errors are no longer differentiated (the same thing was rendering either way)
- Unused code for document deletion was removed ;(
- The DocumentPreviewModal is now rendered directly from the pane, and the DocumentTable is much dumber

### Checklist

- [x] Code is finished
- [ ] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/pulls?q=is%3Apr+is%3Aopen+label%3Arelease), or if the previous PR is merging into master then create a new release candidate PR for the next version following [the Slab doc](https://beyond-essential.slab.com/posts/merging-a-tamanu-ticket-okxp8s4s#h0y52-creating-a-release-candidate-pr))
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

### CODE REVIEW

**Review by NavarroEmilioLuis — COMMENTED** [review]
This is quite a large refactor, I think most is fine and called for, but I think we probably want to address if we need to prevent the app from closing on submission.

**Review by mcccclean — CHANGES_REQUESTED** [review]
Quite a few change requests on this sorry - but it's quite a big & complex PR so don't take that as a criticism! Well done on a huge effort :clap:

**Review by mcccclean — CHANGES_REQUESTED** [review]
Some more changes - sorry for the turnaround time on this one :weary:

**Review by stretchkennedy — CHANGES_REQUESTED** [review]

**Review by stretchkennedy — CHANGES_REQUESTED** [review]
- Ignoring the `type`/`source` confusion in the UI for now until Megs can look at it
- One gotcha with endpoint
Otherwise LGTM

**Review by stretchkennedy — APPROVED** [review]

**Pull request merged**
