### PR TITLE
feat(sync): SAV-747: Change build sync filter

### PR DESCRIPTION
**Pull request by chris-bes**
### Changes
- Change build sync filter

### Deploys

- [ ] **Deploy to Tamanu Internal** 

### Remember to...

- ...write or update tests
- ...add UI screenshots and **testing notes** to the Linear issue
- ...add any **manual upgrade steps** to the Linear issue
- ...update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly), [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q), or any [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c)
- ...call out additions or changes to **config files** for the deployment team to take note of

### CODE REVIEW

**Review by edmofro — CHANGES_REQUESTED** [review]
Another great PR!

**Review by NavarroEmilioLuis — APPROVED** [review]
WHOOPS

**Review by NavarroEmilioLuis — CHANGES_REQUESTED** [review]
Request changes cause I accidentally approved!

**Review by NavarroEmilioLuis — COMMENTED** [review]
Don't have much to add, just marking a couple of places for you to check

**Review by edmofro — APPROVED** [review]
lgtm!

**Pull request merged**
