### PR TITLE
chore(sync): SAV-751: Add tests for Sync lookup table

### PR DESCRIPTION
**Pull request by chris-bes**
### Changes
- Add tests for Sync lookup table

### Deploys

- [x] **Deploy to Tamanu Internal** 

### Remember to...

- ...write or update tests
- ...add UI screenshots and **testing notes** to the Linear issue
- ...add any **manual upgrade steps** to the Linear issue
- ...update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly), [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q), or any [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c)
- ...call out additions or changes to **config files** for the deployment team to take note of

### CODE REVIEW

**Review by NavarroEmilioLuis — COMMENTED** [review]
So here are a couple of comments, don't love we phrase this as a `chore` with changes to the codebase but oh well, I get it. I'll start looking into the tests but they seem to be breaking!

**Review by NavarroEmilioLuis — APPROVED** [review]
Everything looks good to me, I have a couple of suggestions or general questions. But overall, tests make sense, they are passing so I'm good to whatever you decide

**Review by edmofro — APPROVED** [review]
Did a very high level scan and these look like great unit tests, thanks @chris-bes for keeping the standard and coverage high here!!

Approving as codeowner

**Review by NavarroEmilioLuis — APPROVED** [review]
LGTM 👍

**Pull request merged**
