### PR TITLE
EPI-509: Add physicaltype encoding and location group to encounter

### PR DESCRIPTION
**Pull request by stretchkennedy**
### Changes

Adapts FHIR coding for encounter locations to have both a bed and a ward. In future these may be different, but for now they're identical. See [the mapping](https://docs.google.com/spreadsheets/d/1N9Jp8fk8eyn8DHsZj6byHVuBydqROy8jN5JJnY-OKOk/edit#gid=144927121).

~I've got two pending questions to Kurt:~
~1. Confirmation that the locations should be identical and that LocationGroup/Department/etc. isn't involved (refinement was a while ago 😅)~
~2. Whether we should use the uppercase first display strings from http://terminology.hl7.org/CodeSystem/location-physical-type or the lowercase first display strings from our mapping~

~I don't think these need to be answered before reviewing, but I'm happy to take it back out of review if the reviewer thinks we should wait for clarification.~

_Edit: we're using LocationGroup and spec-compliant mapping_

### Checklist

- [x] Code is finished
- [x] Tests are written
- [x] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (look for the draft release [here](https://github.com/beyondessential/tamanu/releases, or create a new one if it doesn't exist following [the Slab doc](https://beyond-essential.slab.com/posts/merging-a-tamanu-ticket-okxp8s4s#h0y52-creating-a-draft-release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

### CODE REVIEW

**Review by edmofro — CHANGES_REQUESTED** [review]
One issue, but otherwise lgtm

**Review by edmofro — APPROVED** [review]

**Review by edmofro — APPROVED** [review]
Even better :+1:

**Review by edmofro — COMMENTED** [review]
@stretchkennedy can you point out what has changed on this since my last review? Because of the force push I can't compare changes or tell what commits have been added

**Review by edmofro — APPROVED** [review]
lgtm

**Review by nick-beyondessential — APPROVED** [review]
LGTM

**Pull request merged**
