### PR TITLE
feat(server): SAV-555 save-pdf-of-senaite-lab-results-coming

### PR DESCRIPTION
**Pull request by kujo4pm**
### Changes

This the card to handle [SAV-555](https://linear.app/bes/issue/SAV-555/save-pdf-of-senaite-lab-results-coming).
Important things to consider in PR:
- Attachments are not to sync with facilities due to size - will only live on central. This logic exists elsewhere in Tamanu.
- LabRequestAttachment is a passthrough table to handle the metadata like title.
- Subsequent posts to `/DiagnosticReport` will not overwrite attachments or LabRequestAttachment but should operate as LabRequestAttachment is a linked list - the top of which has no `replacedBy` relation (=null). We want to keep all valid posts and attachments - not overwrite old ones. Interested in whether this works for the reviewer or if they have a better idea. 

### Checklist

- [x] Code is finished
- [x] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [x] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

### CODE REVIEW

**Review by chris-bes — CHANGES_REQUESTED** [review]
LGTM Kurt! The overall design seems great to me, Just a few change requests!

**Review by NavarroEmilioLuis — COMMENTED** [review]
Seconding all of Chris's points plus one request. (Sorry, was just grabbing context for that other card we were discussing)

**Review by NavarroEmilioLuis — COMMENTED** [review]
Hmmm these bits are missing

**Review by NavarroEmilioLuis — APPROVED** [review]
Aight finally everything is addressed. This should probably be tested and confirmed before merging but I think code is done!

**Pull request closed without merging**
