### PR TITLE
feat(mobile): SAV-727: Patient sync status icon

### PR DESCRIPTION
**Pull request by NavarroEmilioLuis**
### Changes

Updated UI to represent patient sync status (whether patient is marked for sync or not) with an icon.

This work also introduces two components meant to be reused: BaseModal and ConfirmModal, with should help us speed things up and have a consistent way of displaying stuff.

Screenshots of these changes [can be found in here](https://linear.app/bes/issue/SAV-727/represent-if-a-patient-is-marked-for-sync-on-mobile#comment-dd3daca6)

### Deploys

- [x] **Deploy to Tamanu Internal**

### CODE REVIEW

**Review by dannash100 — CHANGES_REQUESTED** [review]
Just some small comments, 
Main thing is to type the props for components on mobile :)

Love your work doe

**Review by dannash100 — APPROVED** [review]
## yes

**Review by dannash100 — APPROVED** [review]
# YESIR

**Review by chris-bes — APPROVED** [review]
code owner stamp!

**Pull request merged**
