### PR TITLE
feat(alerts): TAMOC-248: SQL Proactive alerting for FHIR jobs and various queues

### PR DESCRIPTION
**Pull request by dannash100**
### Changes

Also should this be a folder in root or package?
Still in progress I feel but got sum questions.

- certificate-notification-error
- report-error
- patient-communications-erorr
- ips-error
 
- fhir-queue-not-moving
- fhir-error
- fhir-queue-incredibly-large
- fhir-running-job-long
- fhir-queued-long

### Deploys

- [ ] **Deploy to Tamanu Internal** 

### Remember to...

- ...write or update tests
- ...add UI screenshots and **testing notes** to the Linear issue
- ...add any **manual upgrade steps** to the Linear issue
- ...update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly), [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q), or any [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c)
- ...call out additions or changes to **config files** for the deployment team to take note of

### CODE REVIEW

**Review by NavarroEmilioLuis — COMMENTED** [review]
Not reviewing (at least not yet) but I'd say it depends - if we're only ever going to alert on central then package!

**Review by edmofro — CHANGES_REQUESTED** [review]
Thanks so much for doing this!

**Review by edmofro — COMMENTED** [review]
Couple last changes! Thanks for your work on this I see a lot of after hours

**Review by edmofro — APPROVED** [review]

**Review by edmofro — CHANGES_REQUESTED** [review]
Ah sorry just read question in the description! I disagree with Emilio sorry, I think it should be a folder in root

**Review by edmofro — APPROVED** [review]

**Pull request merged**
