### PR TITLE
fix(sync): SAV-828: Sync task should be in the same process with tamanu-sync

### PR DESCRIPTION
**Pull request by chris-bes**
### Changes
- Sync task should be in the same process with tamanu-sync

### Deploys

- [ ] **Deploy to Tamanu Internal** 

### Remember to...

- ...write or update tests
- ...add UI screenshots and **testing notes** to the Linear issue
- ...add any **manual upgrade steps** to the Linear issue
- ...update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly), [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q), or any [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c)
- ...call out additions or changes to **config files** for the deployment team to take note of

### CODE REVIEW

**Review by NavarroEmilioLuis — CHANGES_REQUESTED** [review]
I'm not very familiar with this separation, but I think this needs to be modified a bit?

**Review by NavarroEmilioLuis — APPROVED** [review]
Oh okay gotcha. LGTM, might want to get a second opinion

**Review by edmofro — APPROVED** [review]
I was thinking we would change the SyncTask to call the api rather than move the task itself into the same process. However this is simpler to implement, and probably just as cohesive, so approved from codeowner perspective!

**Review by passcod — APPROVED** [review]

**Review by rohan-bes — APPROVED** [review]
Approving since it looks like this will work.

A few refactor/code cleanup changes suggested but perhaps they could be address when we merge back to main :+1:

**Pull request merged**
