### PR TITLE
feat(web): NASS-1013: Cambodia Branding

### PR DESCRIPTION
**Pull request by tcaiger**
### Changes
This PR is for making the app name, logo and login screen configurable for Cambodia.

- Add brand name as a .env variable. I chose to use .env variable so that the value is available in the index.html file
- Replacing all tamanu text with the brand name or re-wording text to not have tamanu where appropriate
- Make logo re-usable and switch based on configured brand name
- Switch login screen image based on brand name

### Checklist

- [x] Code is finished
- [x] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

### CODE REVIEW

**Review by dannash100 — CHANGES_REQUESTED** [review]
Some small suggestions and a few things to clean up 💯 🥳

**Review by passcod — CHANGES_REQUESTED** [review]
Putting this as a hard block until addressed: using .env implies making a different build for each deployment, which is not how we're set up.

**Review by dannash100 — CHANGES_REQUESTED** [review]

**Review by dannash100 — APPROVED** [review]
I think this is all looking good, do you think we need to get any sign off on removing branding to support this temporary fix - as if merged it will effect 2.3 cuttoff. Its definetly not a biggie to me personally tho

**Review by Harnesh787 — APPROVED** [review]

**Review by passcod — APPROVED** [review]

**Review by dannash100 — APPROVED** [review]
Just remove that Paraquet

**Pull request merged**
