### PR TITLE
feat(mobile): SAV-578: Mobile filter search UI updates

### PR DESCRIPTION
**Pull request by flynncs**
### Changes

Updated to the `Filter Search` UI on mobile including : 
- Placeholder text in fields
- Dropdown / modal conditional component for Program Registry selection (need to confirm if we want this conditional and if so, what should the cutoff be for switching to modal)
- Cancel button replaced with back arrow
- `Sex` field radio buttons given distinct widths and left aligned text
- 'Program registry' text changed to sentence case
- Field labels given correct font size

Note: Was unable to find a way to remove bottom navbar on filter search screen, as deeply nested in the `HomeTabs` stack - any suggestions appreciated :) 

### Checklist

- [ ] Code is finished
- [ ] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed
- [x] - [x] **Deploy to Tamanu Internal**

### CODE REVIEW

**Review by dannash100 — CHANGES_REQUESTED** [review]
Some ideas! 
Also check that lint failure re the effect 💯 great work out here

**Review by dannash100 — APPROVED** [review]
just a tiny cleanup but ill approve thank you great moves on the changes, looks cleaner fo sure!

**Review by dannash100 — CHANGES_REQUESTED** [review]
Few little things.
just having a think about the hide tabs situ

**Review by dannash100 — APPROVED** [review]
## APPROVE

**Review by anilvkaran — APPROVED** [review]

**Pull request merged**
