### PR TITLE
SAV-345: Additional columns in encounter history

### PR DESCRIPTION
**Pull request by chris-bes**
### Changes
- Added 2 new columns to encounter_history table: modifier_id and change_type
- Modified the migration to migrate the 2 new columns from historical data

### Checklist

- [x] Code is finished
- [x] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

### CODE REVIEW

**Review by georgekamar — APPROVED** [review]
LGTM

**Review by mcccclean — CHANGES_REQUESTED** [review]
Generally LGTM, a couple thoughts and suggestions but happy to hear pushback.

**Review by mcccclean — CHANGES_REQUESTED** [review]
Looking good, one last suggestion

**Review by mcccclean — CHANGES_REQUESTED** [review]
One last tweak :grin:

**Review by mcccclean — APPROVED** [review]

**Pull request merged**
