### PR TITLE
SAV-300: Add loading state for submittable forms

### PR DESCRIPTION
**Pull request by chris-bes**
### Changes
- Add loading state for submittable forms

Screen Shot 2023-07-14 at 4 37 41 pm

### Checklist

- [x] Code is finished
- [ ] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

### CODE REVIEW

**Review by mcccclean — CHANGES_REQUESTED** [review]
Great start on this, getting this smoothed out has been a long time coming.

**Review by stretchkennedy — DISMISSED** [review]
We accidentally double-reviewed this - whoops! Looking good but I'm wondering if it's worth reworking `<Button />` a bit more to avoid all the variant components.

**Review by mcccclean — CHANGES_REQUESTED** [review]
Few more changes here.

There are a lot of minor cleanups around like, I think a `SubmitButton` or one of its variants should never have a separate `type="submit"` prop, as that's built into its base functionality, and `type="submit"` means we already get `onClick={submitForm}` too.

**Review by mcccclean — CHANGES_REQUESTED** [review]

**Review by mcccclean — APPROVED** [review]

**Review by mcccclean — APPROVED** [review]
LGTM again, nice thinking with the workaround. Comment suggestion only, doesn't need re-review

**Review by mcccclean — APPROVED** [review]
Yep, LGTM - good thinking with the context. Will be good to get this merged so that the new forms that're being built can take advantage of it.

**Review by nick-beyondessential — APPROVED** [review]

**Pull request merged**
