### PR TITLE
feat(auth): NASS-1248: restrict users to facilities via userfacility table

### PR DESCRIPTION
**Pull request by passcod**
### Changes

Basically Cambodia's MVP, implemented while I was listening to that incredibly tedious meeting.

- Makes the `user_facilities` table importable
- If users don't have an association to a facility in this table they get rejected on login
- Supports M:N so one user can "belong" to multiple facilities
- Refactor: clean up admin routes
- Adds a Users admin panel with a list and a create modal — helps testing this
- Adds a `checkPermission` method on User to check permissions on users other than the logged in one, or during auth
- Adds the check to the sync endpoint so that you can't sync if you don't have permission for the facility
- Adds the check to the facility listing endpoint so you can only see facilities for which you have permissions.

### Todo

- [x] Feature-gate it in config to avoid config churn in every other deployment
- [x] Add and implement bypass permission `('login', 'Facility')`
- [x] Mobile
- [x] Central Admin panel

### Checklist

- [x] Code is finished
- [ ] Tests are written
- [x] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

### Deploys

- [x] **Deploy to Tamanu Internal**

### CODE REVIEW

**Review by NavarroEmilioLuis — COMMENTED** [review]
I think everything looks good overall, left a couple of questions and optional suggestions.

**Review by anilvkaran — APPROVED** [review]

**Review by edmofro — COMMENTED** [review]
To check my understanding: `user_facilities` was being used for precisely nothing before, right?

**Review by NavarroEmilioLuis — COMMENTED** [review]
Hmmm okay I have a couple comments but I think everything looks good, will update one file, but the other comment I'm unsure if I'm missing something there 🤔

**Review by NavarroEmilioLuis — APPROVED** [review]
Alright I think everything is done for this one then

PS: adding merge pause cause IDK if this still needs something else

**Pull request merged**
