### PR TITLE
feat(vaccine): NASS-1146: Logic to determine Vaccine statuses

### PR DESCRIPTION
**Pull request by namhoangbes**
### Changes

- Create sql query to implement the logic to determain the vaccine statuses
- Create migration to create vaccine_status_threshold table

### Checklist

- [x] Code is finished
- [ ] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

### CODE REVIEW

**Review by julianam-w — COMMENTED** [review]
May need to consider filtering earlier in the query. The cross join at the start is very resource hungry.

**Review by dannash100 — CHANGES_REQUESTED** [review]
Hey this is really such amazing work congratulations on this and handling all the discussion surrounding this ticket @namhoangbes.

We just need to make it so that caller of the view provides the rights when querying it, that is why we are getting permission error on deployment. I will look into this and hopfully we able to have it sorted for when you start.
In mean time im going to add autodeploy tag to this pr - and test permissions incase Tom C's example was not regular occurence.

**Review by dannash100 — APPROVED** [review]
Just tested on auto deploy and the permission for the new view was created automatically so I am giving it a ✅ 
Keen to check grants on main when its merged

**Review by julianam-w — COMMENTED** [review]
Thanks for making the modifications. Looks good aside from a few minor bugs.

**Pull request merged**
