### PR TITLE
feat(sync): SAV-744: Sync lookup table

### PR DESCRIPTION
**Pull request by chris-bes**
### Changes
- Sync lookup table

### Deploys

- [x] **Deploy to Tamanu Internal** 

### Remember to...

- ...write or update tests
- ...add UI screenshots and **testing notes** to the Linear issue
- ...add any **manual upgrade steps** to the Linear issue
- ...update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly), [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q), or any [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c)
- ...call out additions or changes to **config files** for the deployment team to take note of

### CODE REVIEW

**Review by NavarroEmilioLuis — COMMENTED** [review]
Okay, I'm still trying to grasp the core work inside `snapshotOutgoingChanges` and `updateLookupTable` files, but I have some comments/questions ATM. Also we have some tests that are breaking!

**Review by edmofro — CHANGES_REQUESTED** [review]
Plenty of suggestions, but this is really really awesome stuff @chris-bes!

**Review by edmofro — CHANGES_REQUESTED** [review]
Thanks Chris!

Because we use a util to set defaults in the next PR, I think we should go back to your first step on this which was passing through the whole `select` rather than the more confusing `extraFilterColumnSelect`. Can do that here or straight in the next PR if you like.

**Review by edmofro — APPROVED** [review]
lgtm!

**Review by edmofro — APPROVED** [review]
Great final test, thanks for that

**Review by edmofro — APPROVED** [review]

**Review by Harnesh787 — APPROVED** [review]

**Pull request merged**
