### PR TITLE
EPI-668 Deletion status update on Survey Screen Component

### PR DESCRIPTION
**Pull request by biaoli0**
### Manual Changes
Run subcommand: node dist deletedRecords --migrate SurveyScreenComponent

### Changes
Previously in [EPI-573](https://linear.app/bes/issue/EPI-573/data-deletion-tasks-survey-screen-components), we decided to add deletion status to SurveyScreenComponent, and use it as a the source of soft deletion. Now we want to simplify the logic to:
1. Still use `deletedAt` for soft deletion, instead of deletion status.
2. Still keep the deletion status.
3. Sync down `deletedAt` to lan and mobile.

Enable soft deletion on mobile/lan
### Checklist

- [ ] Code is finished
- [ ] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

### CODE REVIEW

**Review by NavarroEmilioLuis — COMMENTED** [review]
I have lots of questions. Mainly I'm a bit confused about why `deletionStatus` and `deletedAt` have to coexist?

Also, I think that using `force` on the unit tests might be hiding an underlying issue, why does this change affect them in such way?

**Review by NavarroEmilioLuis — CHANGES_REQUESTED** [review]
Hey, thank you for going through the questions. I have a couple more requests but I think this looks good! Let me know what you think, most are suggestions and double checks.

**Review by NavarroEmilioLuis — APPROVED** [review]
Alrighty LGTM!

**Review by NavarroEmilioLuis — APPROVED** [review]
Looks good just one minor observation on a test name

**Review by chris-bes — CHANGES_REQUESTED** [review]
Really nice changes! I just have some tiny suggestions

**Review by chris-bes — APPROVED** [review]
I reviewed the sync part and LGTM!

**Review by edmofro — COMMENTED** [review]
@biaoli0 so sorry, I've had this on my list to take a look at since you posted it in codeowners. I was intending to leave the official review to @chris-bes, but it turns out I do have some opinions (what's new), so I'm a bit late here but please take a look at my comments

Overall great work btw! This will solve some really awkward parts of the sync system.

**Pull request merged**
