### PR TITLE
NASS-855: Add db_role to report_definitions column migration

### PR DESCRIPTION
**Pull request by tcodling**
### Changes

~~This card adds a new column to the `report_definitions` table that contains a string defining what hardcoded DB reporting user should be used to run the report (either `tamanu_dataset_reporting` or `tamanu_raw_reporting`. This is part of a bigger project that is adding different permissions regarding which schema to access when creating db defined reports.~~

~~All pre-existing DB defined reports are set to `tamanu_raw_reporting` when the migration is run.~~

After some discussion we decided to make these users/roles configurable. Now this PR covers the migration adding the new column and filling the db reporting role of already created reports with the "raw" reporting role name defined in the config.

I have also setup a new key in the DB section of config for sync and lan called "reportCredientials" that contains a "raw" and "dataset" postgres user credentials.

```
"reportCredentials": {
      "raw": {
        "username": "",
        "password": ""
      },
     "dataset": {
        "username": "",
        "password": ""
      }
    }
```

### Checklist

- [x] Code is finished
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

### CODE REVIEW

**Review by stretchkennedy — CHANGES_REQUESTED** [review]
One potential gotcha with denormalising the db role name like this (but LMK if I've missed something, there's probably a lot of design context I have no idea about 😅 )

**Review by stretchkennedy — DISMISSED** [review]
LGTM 👍 

See comment for one caveat, but if Edwin's cool with it then all good

**Review by stretchkennedy — CHANGES_REQUESTED** [review]
Nearly all LGTM! One gotcha about validating the value of `dbRole` against the values of the constants, other than that it's great 😄

**Review by stretchkennedy — APPROVED** [review]
LGTM :shipit:

**Review by anilvkaran — APPROVED** [review]

**Pull request merged**
