### PR TITLE
feat(settings): NASS-1108: Settings schema

### PR DESCRIPTION
**Pull request by flynncs**
### Changes

Implements a schema for settings., along with tests.

### Deploys

- [ ] **Deploy to Tamanu Internal** 

### Remember to...

- ...write or update tests
- ...add UI screenshots and **testing notes** to the Linear issue
- ...add any **manual upgrade steps** to the Linear issue
- ...update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly), [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q), or any [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c)
- ...call out additions or changes to **config files** for the deployment team to take note of

### CODE REVIEW

**Review by jaskfla — COMMENTED** [review]
I’ll let someone more qualified do an actual review, but just leaving two small TypeScript nitpicks I’ve spotted since branching off your branch

Looks like some neat stuff here 🎉

**Review by dannash100 — COMMENTED** [review]
A few little things, ill keep reviewing

**Review by dannash100 — CHANGES_REQUESTED** [review]
An important one re the need to descriptions on settings section

**Review by dannash100 — COMMENTED** [review]
Hey this is such amazing work @flynncs I love the detail of the tests.
One last little thing is to add some more consistency around the way you are checking typeof and stuff across the utils if possible. Then it a tick

**Review by dannash100 — APPROVED** [review]
Hey actully mostly all optional stuff now - Really great stuff

**Pull request merged**
