### PR TITLE
tweak(sync): SAV-740: Restart long running syncs

### PR DESCRIPTION
**Pull request by NavarroEmilioLuis**
### Changes

This is meant to handle the long snapshots without restarting the server... this approach seems to work on my local tests (setting up a config very low and everytime it gets the error, increase with an external variable), however the logging is not great as we end up changing the error with the sync stale cleaner. Aside from that, servers do not restart and syncs start again!

```
sync-notes=# SELECT created_at, snapshot_started_at, completed_at, error FROM sync_sessions ORDER BY created_at DESC LIMIT 10;
         created_at         |      snapshot_started_at      |        completed_at        |                           error
----------------------------+-------------------------------+----------------------------+------------------------------------------------------------
 2024-08-04 20:22:00.453-05 | 2024-08-04 20:22:01.599723-05 | 2024-08-04 20:22:02.643-05 |
 2024-08-04 20:21:00.764-05 | 2024-08-04 20:21:01.912668-05 | 2024-08-04 20:21:02.96-05  |
 2024-08-04 20:20:00.711-05 | 2024-08-04 20:20:01.867901-05 | 2024-08-04 20:20:02.919-05 |
 2024-08-04 20:19:00.818-05 |                               | 2024-08-04 20:20:00.689-05 | Session marked as completed due to its device reconnecting
 2024-08-04 20:18:00.981-05 |                               | 2024-08-04 20:19:00.795-05 | Session marked as completed due to its device reconnecting
 2024-08-04 20:17:00.557-05 |                               | 2024-08-04 20:18:00.958-05 | Session marked as completed due to its device reconnecting
 2024-08-04 20:16:21.112-05 |                               | 2024-08-04 20:17:00.537-05 | Session marked as completed due to its device reconnecting
 2024-08-04 20:13:00.582-05 |                               | 2024-08-04 20:16:21.088-05 | Session marked as completed due to its device reconnecting
 2024-08-04 20:12:57.665-05 |                               | 2024-08-04 20:13:00.559-05 | Session marked as completed due to its device reconnecting
 2024-08-04 20:11:00.266-05 | 2024-08-04 20:11:01.400037-05 | 2024-08-04 20:11:02.445-05 |
(10 rows)
```

### Deploys

- [ ] **Deploy to Tamanu Internal**

### CODE REVIEW

**Review by chris-bes — APPROVED** [review]
~~LGTM! I know this is urgent so not going to push it hard but might be better to have some tests as well? I'm sure it's quite straightforward~~

Requesting changes

**Review by rohan-bes — COMMENTED** [review]
Just checking with this change we don't do anything to kill the snapshotting process if it's timed out yeah? We just start another one? Slight concern about this leading to clients overwhelming a server that's already under load :thinking:

**Review by chris-bes — CHANGES_REQUESTED** [review]
~~Sorry @NavarroEmilioLuis , I just realized that we also need to remove the existing code that throws an error inside setTimeout (that is causing central server to restarts). So requesting changes this time~~

Nevermind I was in the wrong branch 😓

**Review by Harnesh787 — APPROVED** [review]

**Review by rohan-bes — APPROVED** [review]
Thanks for taking the trouble to add tests :pray:

**Review by chris-bes — APPROVED** [review]

**Pull request merged**
