### PR TITLE
feat(central): NASS-1182: Tamanu entity hierarchy model

### PR DESCRIPTION
**Pull request by tcaiger**
### Changes

Add a new relation table for reference data that will enable turning reference data records into a hierarchy.
- data migration
- models
- facility-server endpoint

Out of scope:
- mobile (https://linear.app/bes/issue/NASS-1191/mobile-tamanu-entity-hierarchy)
- linking facilities to the hierarchy (https://linear.app/bes/issue/NASS-1111/health-center-entity-hierarchy)
- front end (https://linear.app/bes/issue/NASS-1151/cascading-entity-hierarchy-select-component)
- importing and exporting (https://linear.app/bes/issue/NASS-1150/importerexporter-util-for-entity-hierarchy)

### Checklist

- [x] Code is finished
- [x] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

### CODE REVIEW

**Review by dannash100 — COMMENTED** [review]
First set of comments, just gonna keep looking through

**Review by dannash100 — COMMENTED** [review]
Last few comments

**Review by edmofro — COMMENTED** [review]
Hey, I haven't looked across most files but did drill down pretty hard on `ReferenceData.js`, sorry for the density of comments!

Happy to talk any through and hear pushback, as always :-)

**Review by edmofro — CHANGES_REQUESTED** [review]
One last change from my end plz: swapping the `:id` and `ancestors` in the api endpoint

**Review by edmofro — APPROVED** [review]
lgtm :-)

**Review by dannash100 — APPROVED** [review]
Love it! Amazing work

**Review by dannash100 — CHANGES_REQUESTED** [review]
Hey! just saw that model keys for ReferenceDataRelation should be camel case 🙏

**Review by dannash100 — APPROVED** [review]
Thank u!

**Pull request merged**
