### PR TITLE
NASS-682: Fix incorrect pagination on ImagingRequest table

### PR DESCRIPTION
**Pull request by mcccclean**
### Changes

NOTE: This PR also includes a little bit of a rearrange of the existing tests to make it a bit cleaner to write the new ones. I haven't touched the internal logic of the other tests, the only new ones are in the `pagination` at the bottom.

The query for ImagingRequests was joining the ImagingResults relation in a strange way - the result would include a row for each ImagingResult and still obey the LIMIT 10, and then Sequelize would filter out the duplicates (reformatting them as an associated array on the final ImagingRequest object), resulting in fewer results per page than we'd expect.

The fix was to replace the included relation in the querybuilder with an included _attribute_ using a raw SQL subquery.

### Checklist

- [x] Code is finished
- [x] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/pulls?q=is%3Apr+is%3Aopen+label%3Arelease), or if the previous PR is merging into master then create a new release candidate PR for the next version following [the Slab doc](https://beyond-essential.slab.com/posts/merging-a-tamanu-ticket-okxp8s4s#h0y52-creating-a-release-candidate-pr))
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

### CODE REVIEW

**Review by chris-bes — CHANGES_REQUESTED** [review]
I just have 1 question about the removed filter, otherwise LGTM!

**Review by dannash100 — APPROVED** [review]
@chris-bes This was a hectic fix thanks for all involved 🥳 ! Feels a little bit like pushing sequelize to do what it doesnt want to do in this endpoint - so probably really good candidate for rewrite in SQL
Do you think there is any major potential performance implications of double subquery in this endpoint now?

**Review by dannash100 — CHANGES_REQUESTED** [review]
Oh actully relevant test failure re ```"message": "(0 , _sequelize.literal) is not a function"```

**Review by dannash100 — APPROVED** [review]
So sick! love it 💯

**Review by chris-bes — APPROVED** [review]

**Pull request merged**
