### PR TITLE
feat(omniserver): NASS-1304: Handle multiple facilities in sync

### PR DESCRIPTION
**Pull request by dannash100**
### Changes
**Into omniserver epic**

All tests passing 🥳 

- Sync completes with serverFacilityIds
- Central and facility tests updated to reflect changes
- Few new tests for multi facility id and for survey codes supporting setting overrides 

 a few facility tests that broke from changes to fix still

### Deploys

- [ ] **Deploy to Tamanu Internal** 

### Remember to...

- ...write or update tests
- ...add UI screenshots and **testing notes** to the Linear issue
- ...add any **manual upgrade steps** to the Linear issue
- ...update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly), [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q), or any [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c)
- ...call out additions or changes to **config files** for the deployment team to take note of

### CODE REVIEW

**Review by dannash100 — COMMENTED** [review]
Some comments

**Review by chris-bes — CHANGES_REQUESTED** [review]
Looks great to me! I just have a few questions

**Review by chris-bes — APPROVED** [review]
LGTM! Just nit picking 1 last thing

**Review by edmofro — CHANGES_REQUESTED** [review]
Loads of unrelated changes in here, tried to scan my eye over the ones that are actually for the PR but probably missed some stuff. Happy that @chris-bes has reviewed thoroughly though! I just have one additional request

**Review by edmofro — APPROVED** [review]
Oh so we actually don't use it anywhere, it _is_ just for diagnostic purposes? Probs would've been fine as TEXT then, but still nice to have this - thanks!

**Pull request merged**
